### ISSUE TITLE
SvgCanvas: <text style="font: ..."> is not supported by some libraries

### ISSUE THREAD

**Issue by vakorol** [shellyln/red-agate#1]
The `<text>` tags in the SVGs produced by `SvgCanvas.render`, style the fonts using `style="font: ...."`, which is not well supported by some libraries, including cairosvg and inkscape. Maybe split the font style to separate definitions like "font-family", "font-size", etc?

**Comment by shellyln** [comment]
Hi @vakorol !
I think SVG1.1 spec (10.10 Font selection properties) says `font` is valid "shorthand" style property.

https://www.w3.org/TR/SVG11/text.html#AlignmentProperties

And HTML5 Canvas API `ctx.font` property uses the same syntax as the CSS `font` property.

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

**Comment by vakorol** [comment]
Yes, i agree, but still..
I know this is not a problem of red-agate, but it would be really nice if the resulting SVGs were compatible with the popular software that is currently unable to render them properly.

`SvgCanvas` is a great thing, but i bumped into the font problem when converting the resulting SVGs in bulk - I have to parse the resulting XML and substitute all text styles _after_ rendering the SVG content. I could've extended `SvgCanvas` and overridden the relevant method for splitting the font style, but it appeared to be quite complicated because most methods of `SvgCanvas` are private and it's not really possible to subclass it without copy-pasting a lot of code.

As to parsing the "font" property - i use [css-font-parser](https://github.com/bramstein/css-font-parser), which seems to work fine with the styles produced by `SvgCanvas`.

**Comment by shellyln** [comment]
I will consider whether to allow overrides, split properties, or some other way.
`css-font-parser` looks good and is featherweight.
But I want to avoid this library having external dependencies.

https://github.com/shellyln/red-agate/blob/a682df579de737b86ee427cd5b6df1e55aba1644/packages/red-agate-svg-canvas/src/drawing/canvas/SvgCanvas.ts#L1134

**Comment by shellyln** [comment]
New branch added:
https://github.com/shellyln/red-agate/tree/feature-svg-canvas-font-styles-override
(16346a9116491579eb684881bffa3c4bdc9fdedf)

**Comment by shellyln** [comment]
Inkscape probably understands only part of the `font` (`font-size` is not applied).

![inkscape-0-92-4](https://user-images.githubusercontent.com/2476815/75248070-c07a8080-5816-11ea-8e83-d843a0c72d18.png)

[sample.svg.txt](https://github.com/shellyln/red-agate/files/4249989/download.svg.txt)

**Comment by vakorol** [comment]
Yes, exactly.
And `cairosvg` ignores it completely (https://cairosvg.org/svg_support/#styling).
It seems to me that ImageMagick does not fully support `font` in the `convert` utility (at least the sizes are ignored).

**Comment by shellyln** [comment]
Hi, @vakorol 
Is it possible to solve the problem 16346a9116491579eb684881bffa3c4bdc9fdedf way?

I don't think this is a good OOP pattern, and many are not affected by this fix, but also have no direct benefit.
But font rendering has different problems for each client applications...🤔

**Comment by vakorol** [comment]
The proposed solution, although being narrow-targeted at the 'font' problem, will definitely help.
Actually, it could probably be the best solution at the moment as it requires the least effort. At first I thought that it'd be nice to make most of the `get*Attributes` methods "protected", but maybe it doesn't make much sense..

**Comment by shellyln** [comment]
red-agate-svg-canvas `v0.3.1` has published to NPM. (1d569e306b92d74b8b34d265bc47414be05762bb)

**Comment by vakorol** [comment]
Great news, thanks!

**Comment by vakorol** [comment]
I tested extending `SvgCanvas` and overriding `getTextFontStyles`, and it works. Therefore, I am closing the ticket.
